feat: update
CAFECA-IO/TideBit-DeFi pull request #1256
Opened 2023-09-25 09:27 UTC by TzuHanLiang

### DEVELOP

### CHECK LIST

- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new Library: 0
- new Class / Component:  0
- new loop: 0
- high risk: 0
- new sql: 0

### UML

- [Sequence Diagram 001 (interaction between user, frontend and backend)](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00001.md)
- [Sequence Diagram 002 (background mechanism)](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md)
- [Component Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCP00001.md)
- [Class Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCD00001.md)
- [Global context document](https://www.notion.so/Global-Context-public-d93ac7c941c94fb6b173d34a7bc4e959)
- [Table of interface](https://github.com/CAFECA-IO/EventReport/blob/main/meeting/20230106_tbd_mvp.md)

2023-09-26 03:36 UTC, arealclimber requested changes
改完後應該就沒問題了

2023-09-26 03:36 UTC, arealclimber commented on src/lib/safe_math.ts
>    static isNumber(str: string | number) {
經過測試，#1213 描述的問題不會再發生，使用 isNumber 的地方不會因為傳入 undefined 而發生網站 crash 。

更改後的 isNumber 有兩個建議改進的部分：

1. 在 isNumber 函數中，有一個邏輯錯誤。 當檢查 str 是否為字串或數字時，條件應該使用邏輯或 (||) 而不是邏輯與 (&&)。 當前的條件會導致函數始終傳回 false。

請將：

```jsx

if (typeof str !== 'string' || typeof str !== 'number') {
  return false;
}

```

更改為：

```jsx

if (typeof str !== 'string' && typeof str !== 'number') {
  return false;
}

```

2. Regular Expression 正則表達式是檢查字符串是否符合格式，Javascript 會自動將 number 轉成 string 來檢查，允許開發者在不同類型的值之間進行操作，而不需要明確地將它們轉換為相同的類型；我這邊建議使用正則表達式檢查數字時明確地將數字轉換為字符串。這樣可以使程式碼更清晰，並且避免未來可能出現的錯誤或混淆。

```jsx
return numReg.test(str.toString());
```

2023-09-27 03:30 UTC, arealclimber approved these changes

2023-09-28 08:05 UTC, Luphia approved these changes
- no bug found

2023-09-28 08:05 UTC, merged